/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IngressoRouteImport } from './routes/ingresso'
import { Route as FormularioRouteImport } from './routes/formulario'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTempoAcessoRouteImport } from './routes/_authenticated/tempo-acesso'
import { Route as AuthenticatedRelatorioRouteImport } from './routes/_authenticated/relatorio'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedExecutivosRouteImport } from './routes/_authenticated/executivos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCorretoresRouteImport } from './routes/_authenticated/corretores'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedVendasIndexRouteImport } from './routes/_authenticated/vendas.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicWebhookRouteImport } from './routes/api/public/webhook'
import { Route as ApiPublicOnesignalTestRouteImport } from './routes/api/public/onesignal-test'
import { Route as ApiPublicLeadRouteImport } from './routes/api/public/lead'
import { Route as ApiPublicGoogleOauthCallbackRouteImport } from './routes/api/public/google-oauth-callback'
import { Route as ApiPublicCronUnattendedRouteImport } from './routes/api/public/cron-unattended'
import { Route as ApiPublicCronReunioesInstitucionaisRouteImport } from './routes/api/public/cron-reunioes-institucionais'
import { Route as ApiPublicCronReuniaoLembretesRouteImport } from './routes/api/public/cron-reuniao-lembretes'
import { Route as ApiPublicCronLauraResumoDiarioRouteImport } from './routes/api/public/cron-laura-resumo-diario'
import { Route as AuthenticatedVendasPipelineRouteImport } from './routes/_authenticated/vendas.pipeline'
import { Route as AuthenticatedVendasLeadsRouteImport } from './routes/_authenticated/vendas.leads'
import { Route as AuthenticatedVendasAgendaRouteImport } from './routes/_authenticated/vendas.agenda'
import { Route as AuthenticatedLeadsLeadIdRouteImport } from './routes/_authenticated/leads.$leadId'
import { Route as AuthenticatedExecutivosIdRouteImport } from './routes/_authenticated/executivos.$id'
import { Route as AuthenticatedAdminPagamentosRouteImport } from './routes/_authenticated/admin.pagamentos'
import { Route as AuthenticatedAdminInadimplentesRouteImport } from './routes/_authenticated/admin.inadimplentes'
import { Route as AuthenticatedAdminImoveisRouteImport } from './routes/_authenticated/admin.imoveis'
import { Route as AuthenticatedAdminContratosRouteImport } from './routes/_authenticated/admin.contratos'

const IngressoRoute = IngressoRouteImport.update({
  id: '/ingresso',
  path: '/ingresso',
  getParentRoute: () => rootRouteImport,
} as any)
const FormularioRoute = FormularioRouteImport.update({
  id: '/formulario',
  path: '/formulario',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTempoAcessoRoute =
  AuthenticatedTempoAcessoRouteImport.update({
    id: '/tempo-acesso',
    path: '/tempo-acesso',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatorioRoute = AuthenticatedRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExecutivosRoute = AuthenticatedExecutivosRouteImport.update({
  id: '/executivos',
  path: '/executivos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCorretoresRoute = AuthenticatedCorretoresRouteImport.update({
  id: '/corretores',
  path: '/corretores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasIndexRoute =
  AuthenticatedVendasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVendasRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicWebhookRoute = ApiPublicWebhookRouteImport.update({
  id: '/api/public/webhook',
  path: '/api/public/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOnesignalTestRoute = ApiPublicOnesignalTestRouteImport.update({
  id: '/api/public/onesignal-test',
  path: '/api/public/onesignal-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadRoute = ApiPublicLeadRouteImport.update({
  id: '/api/public/lead',
  path: '/api/public/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleOauthCallbackRoute =
  ApiPublicGoogleOauthCallbackRouteImport.update({
    id: '/api/public/google-oauth-callback',
    path: '/api/public/google-oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronUnattendedRoute = ApiPublicCronUnattendedRouteImport.update({
  id: '/api/public/cron-unattended',
  path: '/api/public/cron-unattended',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronReunioesInstitucionaisRoute =
  ApiPublicCronReunioesInstitucionaisRouteImport.update({
    id: '/api/public/cron-reunioes-institucionais',
    path: '/api/public/cron-reunioes-institucionais',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronReuniaoLembretesRoute =
  ApiPublicCronReuniaoLembretesRouteImport.update({
    id: '/api/public/cron-reuniao-lembretes',
    path: '/api/public/cron-reuniao-lembretes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronLauraResumoDiarioRoute =
  ApiPublicCronLauraResumoDiarioRouteImport.update({
    id: '/api/public/cron-laura-resumo-diario',
    path: '/api/public/cron-laura-resumo-diario',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedVendasPipelineRoute =
  AuthenticatedVendasPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedVendasRoute,
  } as any)
const AuthenticatedVendasLeadsRoute =
  AuthenticatedVendasLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedVendasRoute,
  } as any)
const AuthenticatedVendasAgendaRoute =
  AuthenticatedVendasAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedVendasRoute,
  } as any)
const AuthenticatedLeadsLeadIdRoute =
  AuthenticatedLeadsLeadIdRouteImport.update({
    id: '/$leadId',
    path: '/$leadId',
    getParentRoute: () => AuthenticatedLeadsRoute,
  } as any)
const AuthenticatedExecutivosIdRoute =
  AuthenticatedExecutivosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedExecutivosRoute,
  } as any)
const AuthenticatedAdminPagamentosRoute =
  AuthenticatedAdminPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInadimplentesRoute =
  AuthenticatedAdminInadimplentesRouteImport.update({
    id: '/inadimplentes',
    path: '/inadimplentes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImoveisRoute =
  AuthenticatedAdminImoveisRouteImport.update({
    id: '/imoveis',
    path: '/imoveis',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContratosRoute =
  AuthenticatedAdminContratosRouteImport.update({
    id: '/contratos',
    path: '/contratos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/formulario': typeof FormularioRoute
  '/ingresso': typeof IngressoRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/agenda': typeof AuthenticatedAgendaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/corretores': typeof AuthenticatedCorretoresRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/executivos': typeof AuthenticatedExecutivosRouteWithChildren
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/tempo-acesso': typeof AuthenticatedTempoAcessoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/vendas': typeof AuthenticatedVendasRouteWithChildren
  '/admin/contratos': typeof AuthenticatedAdminContratosRoute
  '/admin/imoveis': typeof AuthenticatedAdminImoveisRoute
  '/admin/inadimplentes': typeof AuthenticatedAdminInadimplentesRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/executivos/$id': typeof AuthenticatedExecutivosIdRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/vendas/agenda': typeof AuthenticatedVendasAgendaRoute
  '/vendas/leads': typeof AuthenticatedVendasLeadsRoute
  '/vendas/pipeline': typeof AuthenticatedVendasPipelineRoute
  '/api/public/cron-laura-resumo-diario': typeof ApiPublicCronLauraResumoDiarioRoute
  '/api/public/cron-reuniao-lembretes': typeof ApiPublicCronReuniaoLembretesRoute
  '/api/public/cron-reunioes-institucionais': typeof ApiPublicCronReunioesInstitucionaisRoute
  '/api/public/cron-unattended': typeof ApiPublicCronUnattendedRoute
  '/api/public/google-oauth-callback': typeof ApiPublicGoogleOauthCallbackRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/onesignal-test': typeof ApiPublicOnesignalTestRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/vendas/': typeof AuthenticatedVendasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/formulario': typeof FormularioRoute
  '/ingresso': typeof IngressoRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/corretores': typeof AuthenticatedCorretoresRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/executivos': typeof AuthenticatedExecutivosRouteWithChildren
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/tempo-acesso': typeof AuthenticatedTempoAcessoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/admin/contratos': typeof AuthenticatedAdminContratosRoute
  '/admin/imoveis': typeof AuthenticatedAdminImoveisRoute
  '/admin/inadimplentes': typeof AuthenticatedAdminInadimplentesRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/executivos/$id': typeof AuthenticatedExecutivosIdRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/vendas/agenda': typeof AuthenticatedVendasAgendaRoute
  '/vendas/leads': typeof AuthenticatedVendasLeadsRoute
  '/vendas/pipeline': typeof AuthenticatedVendasPipelineRoute
  '/api/public/cron-laura-resumo-diario': typeof ApiPublicCronLauraResumoDiarioRoute
  '/api/public/cron-reuniao-lembretes': typeof ApiPublicCronReuniaoLembretesRoute
  '/api/public/cron-reunioes-institucionais': typeof ApiPublicCronReunioesInstitucionaisRoute
  '/api/public/cron-unattended': typeof ApiPublicCronUnattendedRoute
  '/api/public/google-oauth-callback': typeof ApiPublicGoogleOauthCallbackRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/onesignal-test': typeof ApiPublicOnesignalTestRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/vendas': typeof AuthenticatedVendasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/formulario': typeof FormularioRoute
  '/ingresso': typeof IngressoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/corretores': typeof AuthenticatedCorretoresRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/executivos': typeof AuthenticatedExecutivosRouteWithChildren
  '/_authenticated/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/relatorio': typeof AuthenticatedRelatorioRoute
  '/_authenticated/tempo-acesso': typeof AuthenticatedTempoAcessoRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRouteWithChildren
  '/_authenticated/admin/contratos': typeof AuthenticatedAdminContratosRoute
  '/_authenticated/admin/imoveis': typeof AuthenticatedAdminImoveisRoute
  '/_authenticated/admin/inadimplentes': typeof AuthenticatedAdminInadimplentesRoute
  '/_authenticated/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/_authenticated/executivos/$id': typeof AuthenticatedExecutivosIdRoute
  '/_authenticated/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/_authenticated/vendas/agenda': typeof AuthenticatedVendasAgendaRoute
  '/_authenticated/vendas/leads': typeof AuthenticatedVendasLeadsRoute
  '/_authenticated/vendas/pipeline': typeof AuthenticatedVendasPipelineRoute
  '/api/public/cron-laura-resumo-diario': typeof ApiPublicCronLauraResumoDiarioRoute
  '/api/public/cron-reuniao-lembretes': typeof ApiPublicCronReuniaoLembretesRoute
  '/api/public/cron-reunioes-institucionais': typeof ApiPublicCronReunioesInstitucionaisRoute
  '/api/public/cron-unattended': typeof ApiPublicCronUnattendedRoute
  '/api/public/google-oauth-callback': typeof ApiPublicGoogleOauthCallbackRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/onesignal-test': typeof ApiPublicOnesignalTestRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/vendas/': typeof AuthenticatedVendasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/formulario'
    | '/ingresso'
    | '/admin'
    | '/agenda'
    | '/configuracoes'
    | '/corretores'
    | '/dashboard'
    | '/executivos'
    | '/leads'
    | '/notificacoes'
    | '/pipeline'
    | '/relatorio'
    | '/tempo-acesso'
    | '/usuarios'
    | '/vendas'
    | '/admin/contratos'
    | '/admin/imoveis'
    | '/admin/inadimplentes'
    | '/admin/pagamentos'
    | '/executivos/$id'
    | '/leads/$leadId'
    | '/vendas/agenda'
    | '/vendas/leads'
    | '/vendas/pipeline'
    | '/api/public/cron-laura-resumo-diario'
    | '/api/public/cron-reuniao-lembretes'
    | '/api/public/cron-reunioes-institucionais'
    | '/api/public/cron-unattended'
    | '/api/public/google-oauth-callback'
    | '/api/public/lead'
    | '/api/public/onesignal-test'
    | '/api/public/webhook'
    | '/admin/'
    | '/vendas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/formulario'
    | '/ingresso'
    | '/agenda'
    | '/configuracoes'
    | '/corretores'
    | '/dashboard'
    | '/executivos'
    | '/leads'
    | '/notificacoes'
    | '/pipeline'
    | '/relatorio'
    | '/tempo-acesso'
    | '/usuarios'
    | '/admin/contratos'
    | '/admin/imoveis'
    | '/admin/inadimplentes'
    | '/admin/pagamentos'
    | '/executivos/$id'
    | '/leads/$leadId'
    | '/vendas/agenda'
    | '/vendas/leads'
    | '/vendas/pipeline'
    | '/api/public/cron-laura-resumo-diario'
    | '/api/public/cron-reuniao-lembretes'
    | '/api/public/cron-reunioes-institucionais'
    | '/api/public/cron-unattended'
    | '/api/public/google-oauth-callback'
    | '/api/public/lead'
    | '/api/public/onesignal-test'
    | '/api/public/webhook'
    | '/admin'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/formulario'
    | '/ingresso'
    | '/_authenticated/admin'
    | '/_authenticated/agenda'
    | '/_authenticated/configuracoes'
    | '/_authenticated/corretores'
    | '/_authenticated/dashboard'
    | '/_authenticated/executivos'
    | '/_authenticated/leads'
    | '/_authenticated/notificacoes'
    | '/_authenticated/pipeline'
    | '/_authenticated/relatorio'
    | '/_authenticated/tempo-acesso'
    | '/_authenticated/usuarios'
    | '/_authenticated/vendas'
    | '/_authenticated/admin/contratos'
    | '/_authenticated/admin/imoveis'
    | '/_authenticated/admin/inadimplentes'
    | '/_authenticated/admin/pagamentos'
    | '/_authenticated/executivos/$id'
    | '/_authenticated/leads/$leadId'
    | '/_authenticated/vendas/agenda'
    | '/_authenticated/vendas/leads'
    | '/_authenticated/vendas/pipeline'
    | '/api/public/cron-laura-resumo-diario'
    | '/api/public/cron-reuniao-lembretes'
    | '/api/public/cron-reunioes-institucionais'
    | '/api/public/cron-unattended'
    | '/api/public/google-oauth-callback'
    | '/api/public/lead'
    | '/api/public/onesignal-test'
    | '/api/public/webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/vendas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FormularioRoute: typeof FormularioRoute
  IngressoRoute: typeof IngressoRoute
  ApiPublicCronLauraResumoDiarioRoute: typeof ApiPublicCronLauraResumoDiarioRoute
  ApiPublicCronReuniaoLembretesRoute: typeof ApiPublicCronReuniaoLembretesRoute
  ApiPublicCronReunioesInstitucionaisRoute: typeof ApiPublicCronReunioesInstitucionaisRoute
  ApiPublicCronUnattendedRoute: typeof ApiPublicCronUnattendedRoute
  ApiPublicGoogleOauthCallbackRoute: typeof ApiPublicGoogleOauthCallbackRoute
  ApiPublicLeadRoute: typeof ApiPublicLeadRoute
  ApiPublicOnesignalTestRoute: typeof ApiPublicOnesignalTestRoute
  ApiPublicWebhookRoute: typeof ApiPublicWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ingresso': {
      id: '/ingresso'
      path: '/ingresso'
      fullPath: '/ingresso'
      preLoaderRoute: typeof IngressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulario': {
      id: '/formulario'
      path: '/formulario'
      fullPath: '/formulario'
      preLoaderRoute: typeof FormularioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tempo-acesso': {
      id: '/_authenticated/tempo-acesso'
      path: '/tempo-acesso'
      fullPath: '/tempo-acesso'
      preLoaderRoute: typeof AuthenticatedTempoAcessoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio': {
      id: '/_authenticated/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AuthenticatedRelatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/executivos': {
      id: '/_authenticated/executivos'
      path: '/executivos'
      fullPath: '/executivos'
      preLoaderRoute: typeof AuthenticatedExecutivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/corretores': {
      id: '/_authenticated/corretores'
      path: '/corretores'
      fullPath: '/corretores'
      preLoaderRoute: typeof AuthenticatedCorretoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/': {
      id: '/_authenticated/vendas/'
      path: '/'
      fullPath: '/vendas/'
      preLoaderRoute: typeof AuthenticatedVendasIndexRouteImport
      parentRoute: typeof AuthenticatedVendasRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/webhook': {
      id: '/api/public/webhook'
      path: '/api/public/webhook'
      fullPath: '/api/public/webhook'
      preLoaderRoute: typeof ApiPublicWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/onesignal-test': {
      id: '/api/public/onesignal-test'
      path: '/api/public/onesignal-test'
      fullPath: '/api/public/onesignal-test'
      preLoaderRoute: typeof ApiPublicOnesignalTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead': {
      id: '/api/public/lead'
      path: '/api/public/lead'
      fullPath: '/api/public/lead'
      preLoaderRoute: typeof ApiPublicLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-oauth-callback': {
      id: '/api/public/google-oauth-callback'
      path: '/api/public/google-oauth-callback'
      fullPath: '/api/public/google-oauth-callback'
      preLoaderRoute: typeof ApiPublicGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-unattended': {
      id: '/api/public/cron-unattended'
      path: '/api/public/cron-unattended'
      fullPath: '/api/public/cron-unattended'
      preLoaderRoute: typeof ApiPublicCronUnattendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-reunioes-institucionais': {
      id: '/api/public/cron-reunioes-institucionais'
      path: '/api/public/cron-reunioes-institucionais'
      fullPath: '/api/public/cron-reunioes-institucionais'
      preLoaderRoute: typeof ApiPublicCronReunioesInstitucionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-reuniao-lembretes': {
      id: '/api/public/cron-reuniao-lembretes'
      path: '/api/public/cron-reuniao-lembretes'
      fullPath: '/api/public/cron-reuniao-lembretes'
      preLoaderRoute: typeof ApiPublicCronReuniaoLembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-laura-resumo-diario': {
      id: '/api/public/cron-laura-resumo-diario'
      path: '/api/public/cron-laura-resumo-diario'
      fullPath: '/api/public/cron-laura-resumo-diario'
      preLoaderRoute: typeof ApiPublicCronLauraResumoDiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendas/pipeline': {
      id: '/_authenticated/vendas/pipeline'
      path: '/pipeline'
      fullPath: '/vendas/pipeline'
      preLoaderRoute: typeof AuthenticatedVendasPipelineRouteImport
      parentRoute: typeof AuthenticatedVendasRoute
    }
    '/_authenticated/vendas/leads': {
      id: '/_authenticated/vendas/leads'
      path: '/leads'
      fullPath: '/vendas/leads'
      preLoaderRoute: typeof AuthenticatedVendasLeadsRouteImport
      parentRoute: typeof AuthenticatedVendasRoute
    }
    '/_authenticated/vendas/agenda': {
      id: '/_authenticated/vendas/agenda'
      path: '/agenda'
      fullPath: '/vendas/agenda'
      preLoaderRoute: typeof AuthenticatedVendasAgendaRouteImport
      parentRoute: typeof AuthenticatedVendasRoute
    }
    '/_authenticated/leads/$leadId': {
      id: '/_authenticated/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedLeadsRoute
    }
    '/_authenticated/executivos/$id': {
      id: '/_authenticated/executivos/$id'
      path: '/$id'
      fullPath: '/executivos/$id'
      preLoaderRoute: typeof AuthenticatedExecutivosIdRouteImport
      parentRoute: typeof AuthenticatedExecutivosRoute
    }
    '/_authenticated/admin/pagamentos': {
      id: '/_authenticated/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AuthenticatedAdminPagamentosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inadimplentes': {
      id: '/_authenticated/admin/inadimplentes'
      path: '/inadimplentes'
      fullPath: '/admin/inadimplentes'
      preLoaderRoute: typeof AuthenticatedAdminInadimplentesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/imoveis': {
      id: '/_authenticated/admin/imoveis'
      path: '/imoveis'
      fullPath: '/admin/imoveis'
      preLoaderRoute: typeof AuthenticatedAdminImoveisRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contratos': {
      id: '/_authenticated/admin/contratos'
      path: '/contratos'
      fullPath: '/admin/contratos'
      preLoaderRoute: typeof AuthenticatedAdminContratosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminContratosRoute: typeof AuthenticatedAdminContratosRoute
  AuthenticatedAdminImoveisRoute: typeof AuthenticatedAdminImoveisRoute
  AuthenticatedAdminInadimplentesRoute: typeof AuthenticatedAdminInadimplentesRoute
  AuthenticatedAdminPagamentosRoute: typeof AuthenticatedAdminPagamentosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminContratosRoute: AuthenticatedAdminContratosRoute,
  AuthenticatedAdminImoveisRoute: AuthenticatedAdminImoveisRoute,
  AuthenticatedAdminInadimplentesRoute: AuthenticatedAdminInadimplentesRoute,
  AuthenticatedAdminPagamentosRoute: AuthenticatedAdminPagamentosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedExecutivosRouteChildren {
  AuthenticatedExecutivosIdRoute: typeof AuthenticatedExecutivosIdRoute
}

const AuthenticatedExecutivosRouteChildren: AuthenticatedExecutivosRouteChildren =
  {
    AuthenticatedExecutivosIdRoute: AuthenticatedExecutivosIdRoute,
  }

const AuthenticatedExecutivosRouteWithChildren =
  AuthenticatedExecutivosRoute._addFileChildren(
    AuthenticatedExecutivosRouteChildren,
  )

interface AuthenticatedLeadsRouteChildren {
  AuthenticatedLeadsLeadIdRoute: typeof AuthenticatedLeadsLeadIdRoute
}

const AuthenticatedLeadsRouteChildren: AuthenticatedLeadsRouteChildren = {
  AuthenticatedLeadsLeadIdRoute: AuthenticatedLeadsLeadIdRoute,
}

const AuthenticatedLeadsRouteWithChildren =
  AuthenticatedLeadsRoute._addFileChildren(AuthenticatedLeadsRouteChildren)

interface AuthenticatedVendasRouteChildren {
  AuthenticatedVendasAgendaRoute: typeof AuthenticatedVendasAgendaRoute
  AuthenticatedVendasLeadsRoute: typeof AuthenticatedVendasLeadsRoute
  AuthenticatedVendasPipelineRoute: typeof AuthenticatedVendasPipelineRoute
  AuthenticatedVendasIndexRoute: typeof AuthenticatedVendasIndexRoute
}

const AuthenticatedVendasRouteChildren: AuthenticatedVendasRouteChildren = {
  AuthenticatedVendasAgendaRoute: AuthenticatedVendasAgendaRoute,
  AuthenticatedVendasLeadsRoute: AuthenticatedVendasLeadsRoute,
  AuthenticatedVendasPipelineRoute: AuthenticatedVendasPipelineRoute,
  AuthenticatedVendasIndexRoute: AuthenticatedVendasIndexRoute,
}

const AuthenticatedVendasRouteWithChildren =
  AuthenticatedVendasRoute._addFileChildren(AuthenticatedVendasRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCorretoresRoute: typeof AuthenticatedCorretoresRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExecutivosRoute: typeof AuthenticatedExecutivosRouteWithChildren
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRouteWithChildren
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedRelatorioRoute: typeof AuthenticatedRelatorioRoute
  AuthenticatedTempoAcessoRoute: typeof AuthenticatedTempoAcessoRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCorretoresRoute: AuthenticatedCorretoresRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExecutivosRoute: AuthenticatedExecutivosRouteWithChildren,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRouteWithChildren,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedRelatorioRoute: AuthenticatedRelatorioRoute,
  AuthenticatedTempoAcessoRoute: AuthenticatedTempoAcessoRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FormularioRoute: FormularioRoute,
  IngressoRoute: IngressoRoute,
  ApiPublicCronLauraResumoDiarioRoute: ApiPublicCronLauraResumoDiarioRoute,
  ApiPublicCronReuniaoLembretesRoute: ApiPublicCronReuniaoLembretesRoute,
  ApiPublicCronReunioesInstitucionaisRoute:
    ApiPublicCronReunioesInstitucionaisRoute,
  ApiPublicCronUnattendedRoute: ApiPublicCronUnattendedRoute,
  ApiPublicGoogleOauthCallbackRoute: ApiPublicGoogleOauthCallbackRoute,
  ApiPublicLeadRoute: ApiPublicLeadRoute,
  ApiPublicOnesignalTestRoute: ApiPublicOnesignalTestRoute,
  ApiPublicWebhookRoute: ApiPublicWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
