/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FormularioRouteImport } from './routes/formulario'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTempoAcessoRouteImport } from './routes/_authenticated/tempo-acesso'
import { Route as AuthenticatedRelatorioRouteImport } from './routes/_authenticated/relatorio'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCorretoresRouteImport } from './routes/_authenticated/corretores'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as ApiPublicWebhookRouteImport } from './routes/api/public/webhook'
import { Route as ApiPublicOnesignalTestRouteImport } from './routes/api/public/onesignal-test'
import { Route as ApiPublicLeadRouteImport } from './routes/api/public/lead'
import { Route as ApiPublicCronUnattendedRouteImport } from './routes/api/public/cron-unattended'

const FormularioRoute = FormularioRouteImport.update({
  id: '/formulario',
  path: '/formulario',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTempoAcessoRoute =
  AuthenticatedTempoAcessoRouteImport.update({
    id: '/tempo-acesso',
    path: '/tempo-acesso',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatorioRoute = AuthenticatedRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCorretoresRoute = AuthenticatedCorretoresRouteImport.update({
  id: '/corretores',
  path: '/corretores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhookRoute = ApiPublicWebhookRouteImport.update({
  id: '/api/public/webhook',
  path: '/api/public/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOnesignalTestRoute = ApiPublicOnesignalTestRouteImport.update({
  id: '/api/public/onesignal-test',
  path: '/api/public/onesignal-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadRoute = ApiPublicLeadRouteImport.update({
  id: '/api/public/lead',
  path: '/api/public/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronUnattendedRoute = ApiPublicCronUnattendedRouteImport.update({
  id: '/api/public/cron-unattended',
  path: '/api/public/cron-unattended',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/formulario': typeof FormularioRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/corretores': typeof AuthenticatedCorretoresRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/tempo-acesso': typeof AuthenticatedTempoAcessoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/public/cron-unattended': typeof ApiPublicCronUnattendedRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/onesignal-test': typeof ApiPublicOnesignalTestRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/formulario': typeof FormularioRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/corretores': typeof AuthenticatedCorretoresRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/tempo-acesso': typeof AuthenticatedTempoAcessoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/public/cron-unattended': typeof ApiPublicCronUnattendedRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/onesignal-test': typeof ApiPublicOnesignalTestRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/formulario': typeof FormularioRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/corretores': typeof AuthenticatedCorretoresRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/relatorio': typeof AuthenticatedRelatorioRoute
  '/_authenticated/tempo-acesso': typeof AuthenticatedTempoAcessoRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/public/cron-unattended': typeof ApiPublicCronUnattendedRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/onesignal-test': typeof ApiPublicOnesignalTestRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/formulario'
    | '/configuracoes'
    | '/corretores'
    | '/dashboard'
    | '/leads'
    | '/notificacoes'
    | '/pipeline'
    | '/relatorio'
    | '/tempo-acesso'
    | '/usuarios'
    | '/api/public/cron-unattended'
    | '/api/public/lead'
    | '/api/public/onesignal-test'
    | '/api/public/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/formulario'
    | '/configuracoes'
    | '/corretores'
    | '/dashboard'
    | '/leads'
    | '/notificacoes'
    | '/pipeline'
    | '/relatorio'
    | '/tempo-acesso'
    | '/usuarios'
    | '/api/public/cron-unattended'
    | '/api/public/lead'
    | '/api/public/onesignal-test'
    | '/api/public/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/formulario'
    | '/_authenticated/configuracoes'
    | '/_authenticated/corretores'
    | '/_authenticated/dashboard'
    | '/_authenticated/leads'
    | '/_authenticated/notificacoes'
    | '/_authenticated/pipeline'
    | '/_authenticated/relatorio'
    | '/_authenticated/tempo-acesso'
    | '/_authenticated/usuarios'
    | '/api/public/cron-unattended'
    | '/api/public/lead'
    | '/api/public/onesignal-test'
    | '/api/public/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FormularioRoute: typeof FormularioRoute
  ApiPublicCronUnattendedRoute: typeof ApiPublicCronUnattendedRoute
  ApiPublicLeadRoute: typeof ApiPublicLeadRoute
  ApiPublicOnesignalTestRoute: typeof ApiPublicOnesignalTestRoute
  ApiPublicWebhookRoute: typeof ApiPublicWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/formulario': {
      id: '/formulario'
      path: '/formulario'
      fullPath: '/formulario'
      preLoaderRoute: typeof FormularioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tempo-acesso': {
      id: '/_authenticated/tempo-acesso'
      path: '/tempo-acesso'
      fullPath: '/tempo-acesso'
      preLoaderRoute: typeof AuthenticatedTempoAcessoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio': {
      id: '/_authenticated/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AuthenticatedRelatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/corretores': {
      id: '/_authenticated/corretores'
      path: '/corretores'
      fullPath: '/corretores'
      preLoaderRoute: typeof AuthenticatedCorretoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhook': {
      id: '/api/public/webhook'
      path: '/api/public/webhook'
      fullPath: '/api/public/webhook'
      preLoaderRoute: typeof ApiPublicWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/onesignal-test': {
      id: '/api/public/onesignal-test'
      path: '/api/public/onesignal-test'
      fullPath: '/api/public/onesignal-test'
      preLoaderRoute: typeof ApiPublicOnesignalTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead': {
      id: '/api/public/lead'
      path: '/api/public/lead'
      fullPath: '/api/public/lead'
      preLoaderRoute: typeof ApiPublicLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-unattended': {
      id: '/api/public/cron-unattended'
      path: '/api/public/cron-unattended'
      fullPath: '/api/public/cron-unattended'
      preLoaderRoute: typeof ApiPublicCronUnattendedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCorretoresRoute: typeof AuthenticatedCorretoresRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedRelatorioRoute: typeof AuthenticatedRelatorioRoute
  AuthenticatedTempoAcessoRoute: typeof AuthenticatedTempoAcessoRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCorretoresRoute: AuthenticatedCorretoresRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedRelatorioRoute: AuthenticatedRelatorioRoute,
  AuthenticatedTempoAcessoRoute: AuthenticatedTempoAcessoRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FormularioRoute: FormularioRoute,
  ApiPublicCronUnattendedRoute: ApiPublicCronUnattendedRoute,
  ApiPublicLeadRoute: ApiPublicLeadRoute,
  ApiPublicOnesignalTestRoute: ApiPublicOnesignalTestRoute,
  ApiPublicWebhookRoute: ApiPublicWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
